"""utils.pptx — PPTX utility package."""

from utils.pptx.code_templates import (
    add_border_label_function,
    add_border_function,
    create_id_map_function,
    save_helper_info_border_label,
    save_helper_info_border,
    utils_functions,
    documentation,
)

from utils.pptx.operations import (
    emu_to_inches,
    _px_to_pt,
    _parse_font_size,
    _parse_alignment,
    create_poster,
    add_blank_slide,
    save_presentation,
    set_slide_background_color,
    shape_fill_color,
    set_shape_position,
    center_shape_horizontally,
    center_shape_vertically,
    add_image,
    add_line_simple,
    style_shape_border,
    _set_run_font_color,
    add_textbox,
    edit_textbox,
    set_shape_text,
    set_text_style,
    set_paragraph_line_spacing,
    set_shape_text_margins,
    adjust_font_size,
    fill_textframe,
    add_border,
    add_border_hierarchy,
    get_visual_cues,
    get_hierarchy,
    get_hierarchy_by_keys,
    rename_keys_with_name,
)
